services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      POSTGRES_DB: openwebui
      POSTGRES_USER: openwebui
      POSTGRES_PASSWORD: openwebui
    ports:
      - "5433:5432"   # <-- expose to host (localhost:5433)
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:8080"
    environment:
      # Main application database (SQLAlchemy URL)
      # If your password has special characters, URL-encode them.
      DATABASE_URL: postgresql://openwebui:openwebui@db:5432/openwebui

      # Use pgvector for RAG
      VECTOR_DB: pgvector

      # Let OWUI create the 'vector' extension on first boot (requires superuser)
      PGVECTOR_CREATE_EXTENSION: "true"
    volumes:
      - openwebui_data:/app/backend/data
    restart: unless-stopped

volumes:
  openwebui_data:
  pg_data:
